(function () {
  'use strict';
  var feed=null,curated={version:1,entries:[]},api=null,busy=false,warning='',pending=false;
  var remote='https://raw.githubusercontent.com/brokestes/lincoln-christian-broadcast-desk/main/';
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
  function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');}
  function url(s){try{var u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?s:'#';}catch(e){return '#';}}
  function stamp(s){return s&&!isNaN(new Date(s))?new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(s)):'Not verified';}
  function day(s){var p={};new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(s||Date.now())).forEach(function(v){p[v.type]=v.value;});return p.year+'-'+p.month+'-'+p.day;}
  function date(s){return /^20\d{2}-\d{2}-\d{2}$/.test(s||'')?new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',weekday:'short',month:'short',day:'numeric'}):'Date TBD';}
  function time(s){var m=/^([01]\d|2[0-3]):([0-5]\d)$/.exec(s||'');return m?((+m[1])%12||12)+':'+m[2]+' '+(+m[1]>=12?'PM':'AM')+' CT':'Time TBD';}
  function link(s,label){return '<a href="'+esc(url(s))+'" target="_blank" rel="noreferrer">'+esc(label||'Source')+' ↗</a>';}
  function distinctFixtures(schedule){var seen=new Set(),events=schedule.events||[];schedule.events=events.filter(function(e){var key=JSON.stringify([e.date,e.time,norm(e.opponent),e.site,e.district,e.result,e.score,e.opponentScore,e.status,e.kind]);if(seen.has(key))return false;seen.add(key);return true;});schedule.duplicateCount=(schedule.duplicateCount||0)+events.length-schedule.events.length;}
  function validate(value){
    if(!value||value.version!==1||value.mode!=='public-data-only'||value.timeZone!=='America/Chicago'||value.season!=='2026-27'||!value.teams||!value.generatedAt||isNaN(new Date(value.generatedAt)))throw Error('Invalid football feed');
    Object.keys(value.teams).forEach(function(name){var t=value.teams[name];if(!t||!t.schedule||!t.roster)throw Error('Invalid team');
      (t.schedule.events||[]).forEach(function(e){if(typeof e.opponent!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(e.date)||e.score!=null&&!Number.isFinite(e.score)||e.opponentScore!=null&&!Number.isFinite(e.opponentScore))throw Error('Invalid schedule');});
      distinctFixtures(t.schedule);
      [t.roster,value.officialRoster].filter(Boolean).forEach(function(r){if((r.players||[]).length>150)throw Error('Roster too large');(r.players||[]).forEach(function(p){if(typeof p.name!=='string'||typeof p.number!=='string')throw Error('Invalid player');});});
      if(t.stats&&t.stats.tables){if(t.stats.tables.length>30)throw Error('Too many stats');t.stats.tables.forEach(function(s){if(!Array.isArray(s.headers)||!Array.isArray(s.rows)||s.rows.length>150||s.rows.some(function(r){return r.length!==s.headers.length;}))throw Error('Invalid stat table');});}
    });return value;
  }
  function validateCurated(v){if(!v||v.version!==1||!Array.isArray(v.entries)||v.entries.length>100)throw Error('Invalid researched highlights');v.entries.forEach(function(e){if(e.sport!=='football'||typeof e.opponent!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(e.gameDate)||!e.checkedAt||isNaN(new Date(e.checkedAt)))throw Error('Invalid research target');['lincolnStory','opponentStory','keys'].forEach(function(k){(e.sections&&e.sections[k]||[]).forEach(function(f){if(typeof f.text!=='string'||f.text.length>1500||url(f.url)==='#'||typeof f.date!=='string'||!f.date)throw Error('Unsourced highlight');});});});return v;}
  function team(name,game){
    if(!feed)return null;
    var key=Object.keys(feed.teams).find(function(n){return norm(n)===norm(name);});
    if(!key)return null;
    if(game&&name!=='Lincoln Christian'&&!(feed.teams['Lincoln Christian'].schedule.events||[]).some(function(e){return e.date===game.date&&norm(e.opponent)===norm(name);}))return null;
    return feed.teams[key];
  }
  function researchEntry(game){return game&&curated.entries.find(function(e){return e.gameDate===game.date&&norm(e.opponent)===norm(game.opponent);});}
  function statData(){var t=team('Lincoln Christian');return t&&t.stats&&t.stats.tables&&t.stats.tables.length?t.stats:null;}
  function pregameRecord(name,game){var t=team(name,game);if(!t||!game)return '';var games=(t.schedule.events||[]).filter(function(e){return e.date<game.date&&e.status==='completed';});if(!games.length)return '';function record(list){var w=list.filter(function(e){return /^W/.test(e.result);}).length,l=list.filter(function(e){return /^L/.test(e.result);}).length,t=list.length-w-l;return w+'–'+l+(t?'–'+t:'');}var district=games.filter(function(e){return e.district;});return record(games)+(district.length?' · '+record(district)+' district':'');}
  function statDescription(s){return s?'Published coverage: '+(s.games||'unknown')+' games · provider updated '+stamp(s.updatedAt)+' · source checked '+stamp(s.checkedAt)+(s.status==='error'?' · refresh failed; older data retained':''):'Dated snapshot · five games · provider updated Oct. 3, 2026 · checked Oct. 8, 2026';}
  function coverageWarning(name){var t=team(name);if(!t)return 'Not verified for this team.';var s=t.stats,finals=(t.schedule.events||[]).filter(function(e){return e.status==='completed';}).length;
    if(!s)return 'Player stats have not been checked for this matchup yet.';
    if(s.status==='not-published')return 'No player stat tables published on the checked MaxPreps page. Missing stats are not zeros.';
    if(!s.tables||!s.tables.length)return 'Stats could not be refreshed; availability is unverified.';
    return (s.games<finals?'Stats cover '+s.games+' games, but '+finals+' final scores are posted. The latest game’s player stats are still unconfirmed.':'Published game coverage matches the number of posted finals; this does not guarantee every player/stat is recorded.')+(s.status==='error'?' Latest source check failed.':'');
  }
  function result(e){return e.status==='completed'&&e.score!=null&&e.opponentScore!=null?(e.result||'').slice(0,1)+' '+e.score+'–'+e.opponentScore:e.date<day()?'Final not posted':time(e.time);}
  function scheduleTable(schedule,game,printing){var events=schedule.events||[];return '<div class="table-scroll"><table class="'+(printing?'print-stats':'opponent-season-table')+'"><thead><tr><th>Date</th><th>Opponent</th><th>Site</th><th>Result / time</th><th>Context</th></tr></thead><tbody>'+events.map(function(e){var matchup=game&&e.date===game.date&&norm(e.opponent)==='lincolnchristian';return '<tr'+(matchup?' class="lincoln-matchup"':'')+'><td>'+esc(date(e.date))+'</td><td>'+esc(e.opponent)+(matchup?'<small>Lincoln matchup</small>':'')+'</td><td>'+esc(e.site)+'</td><td class="schedule-result">'+esc(result(e))+'</td><td>'+esc(e.district?'District':'Non-district')+(printing?'':' · '+link(e.url||schedule.source,'Game'))+'</td></tr>';}).join('')+'</tbody></table></div>';}
  function printMarkup(sport,game){var t=sport==='football'&&game?team(game.opponent,game):null;if(!t||!t.schedule.events)return '';return '<section class="print-section"><h2>'+esc(game.opponent)+' · season schedule &amp; results</h2><p>Scores are from '+esc(game.opponent)+'’s perspective. Checked '+esc(stamp(t.schedule.checkedAt))+(t.schedule.status==='error'?' · failed refresh; retained data':'')+' · '+esc(t.schedule.source)+'</p>'+scheduleTable(t.schedule,game,true)+'</section>';}
  function statusRow(title,cadence,source,details){return '<article class="source-audit-row"><div><h3>'+esc(title)+'</h3><span class="audit-cadence">'+esc(cadence)+'</span></div><p>'+esc(details)+'</p>'+(source?'<small>Last successful check: '+esc(stamp(source.checkedAt))+(source.status==='error'?' · LATEST ATTEMPT FAILED '+esc(stamp(source.attemptedAt)):'')+'</small>'+link(source.source,'Original source'):'')+'</article>';}
  function render(sport,game){
    var panel=document.getElementById('opponentSchedule'),t=sport==='football'&&game?team(game.opponent,game):null;
    if(panel)panel.innerHTML=!t?'<p class="source-note">'+(sport!=='football'?'Automatic opponent schedules are currently available for football only. Basketball opponent schedules have not been verified.':'No verified schedule loaded for this opponent/date. It will not be guessed.')+'</p>':
      '<div class="opponent-schedule-heading"><div><span class="eyebrow">THE OTHER SIDELINE</span><h2>'+esc(game.opponent)+' '+esc(t.schedule.mascot||'')+'</h2><p>'+esc(t.schedule.season)+' football · published record '+esc(t.schedule.record||'Not listed')+'</p></div>'+link(t.schedule.source,'Full MaxPreps schedule')+'</div><p class="source-note">Completed games, opponents and upcoming dates. Scores are from '+esc(game.opponent)+'’s perspective. Source checked '+esc(stamp(t.schedule.checkedAt))+'. '+(t.schedule.status==='error'?'Refresh failed; last successful schedule retained. ':'')+'Times are Central; unposted results stay unposted.'+(t.schedule.duplicateCount?' '+t.schedule.duplicateCount+' identical duplicate source fixture(s) shown once.':'')+'</p>'+scheduleTable(t.schedule,game,false);
    var audit=document.getElementById('sourceAudit'),lc=team('Lincoln Christian'),entry=researchEntry(game);
    if(audit)audit.innerHTML='<div class="panel-heading split"><div><span class="eyebrow">WHAT ACTUALLY UPDATES</span><h2>Data checks &amp; research status</h2></div><button class="small-btn" id="weeklyRefresh"'+(busy?' disabled':'')+'>'+(busy?'Checking…':'Check latest feed')+'</button></div>'+(warning?'<p class="weekly-warning">'+esc(warning)+'</p>':'')+'<p class="section-hint">Checking a source is not the same as that source publishing new information. Noon is a preparation target, not a guaranteed delivery time.</p>'+
      statusRow('Lincoln football / boys / girls schedules','GitHub · every 3 hours',feed&&feed.officialSchedule,'Official school schedule feed; Home shows each sport’s own check timestamp. Runs with the laptop off.')+
      statusRow('Football opponent schedules & rosters','GitHub · Sundays 8:17 AM and 11:17 AM Tulsa time',t&&t.schedule,'Schedules and published rosters for the football opponents on Lincoln’s schedule. Failed checks retain dated data and warnings. Missing rosters are explicitly flagged.')+
      statusRow('Lincoln football player stats','GitHub · Sunday checks',lc&&lc.stats,statDescription(statData())+'. '+coverageWarning('Lincoln Christian'))+
      statusRow(game?game.opponent+' player stats':'Opponent player stats','GitHub · next scheduled football game',t&&t.stats,game?coverageWarning(game.opponent):'Select a game.')+
      statusRow('Lincoln football news','GitHub · Sunday headline checks',feed&&feed.news,'Latest official article headlines/links only. This collector does not write news analysis or research player backgrounds.')+
      statusRow('History, awards & player-background highlights','Full research run · cloud setup pending',null,entry?'Matchup research completed '+stamp(entry.checkedAt)+'. See each highlighted fact’s source/date.':'No completed full research run published for this matchup. Existing Oct. 8–9 highlights are dated snapshots, not newly verified facts. SKORDLE, I Was At The Game, Tulsa World, VYPE and public athlete profiles are research links—not continuously monitored feeds.')+
      statusRow('Live TurboStats','Every 20 seconds while this page is visible',null,'Separate from season stats. The selected game/date must match. Unrecorded defensive stats are not assumed to be zero.')+
      '<p class="source-note">GitHub jobs can be delayed or fail; source timestamps and warnings are the evidence of a successful check. '+link('https://github.com/brokestes/lincoln-christian-broadcast-desk/actions','View update runs')+' · Your notes stay on this device and are never written by these jobs.</p>';
    var home=document.getElementById('homePrepStatus');if(home)home.innerHTML='<span class="eyebrow">WEEKLY FOOTBALL PREP</span><h2>'+(feed&&feed.target?esc(date(feed.target.date)+' · '+feed.target.opponent):'Next matchup pending')+'</h2><p>Public data checked '+esc(feed?stamp(feed.generatedAt):'Not yet')+'. '+(feed&&feed.failures?esc(feed.failures)+' source checks failed. ':'')+'Full Sunday research: '+(feed&&feed.target&&researchEntry({date:feed.target.date,opponent:feed.target.opponent})?'published':'not yet published')+'.</p><p class="home-footnote">Public checks run with the laptop off. Cloud research setup is not yet verified. Sunday prep targets the next scheduled game, including Thursday games.</p><button class="small-btn" data-home-section="sources">See update status ↗</button>';
    var header=document.getElementById('publicDataDate');if(header)header.textContent=feed?new Date(feed.generatedAt).toLocaleDateString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',year:'numeric'}):'Loading…';
  }
  function fact(text,source,checkedAt,label){return {text:text,url:source,date:checkedAt,label:label||'MaxPreps'};}
  function facts(sport,game){var r={lincolnStory:[],opponentStory:[],keys:[]};if(sport!=='football'||!game)return r;
    var fresh=feed&&game.date>=day(feed.generatedAt)&&team(game.opponent,game),entry=researchEntry(game);
    if(fresh)['Lincoln Christian',game.opponent].forEach(function(name,index){var t=team(name,game);if(!t)return;var key=index?'opponentStory':'lincolnStory',s=t.schedule;
      // Calculate pregame context only from posted games before the selected date; don't leak a later result backward.
      var prior=(s.events||[]).filter(function(e){return e.date<game.date&&e.status==='completed';}),wins=prior.filter(function(e){return /^W/.test(e.result);}).length,losses=prior.filter(function(e){return /^L/.test(e.result);}).length,ties=prior.length-wins-losses;
      r[key].push(fact('RECENT FORM · '+name+': '+wins+'–'+losses+(ties?'–'+ties:'')+' from '+prior.length+' posted finals before this matchup.',s.source,'Source checked '+stamp(s.checkedAt)+(s.status==='error'?' · retained data':'')));
      var last=prior[prior.length-1];if(last)r[key].push(fact('LAST POSTED GAME · '+date(last.date)+': '+result(last)+' vs '+last.opponent+' ('+last.site+').',last.url||s.source,'Checked '+stamp(s.checkedAt)));
      var missing=(s.events||[]).filter(function(e){return e.date<day()&&e.date<game.date&&e.status!=='completed';});if(missing.length)r.keys.push(fact('AWAITING FINAL · '+name+': '+missing.map(function(e){return date(e.date)+' vs '+e.opponent;}).join('; ')+'. Record/stat coverage may lag.',s.source,'Checked '+stamp(s.checkedAt)));
      if(index&&s.districtPlace)r[key].push(fact('DISTRICT WATCH · MaxPreps lists '+s.districtPlace+' in '+s.districtName+', district record '+s.districtRecord+'. This is the provider’s current standing, not a playoff prediction.',s.source,'Checked '+stamp(s.checkedAt)));
    });
    var s=statData();if(fresh&&s){var table=function(name){return s.tables.find(function(t){return t.title===name;});},value=function(t,row,key){return row&&row[t.headers.indexOf(key)];};
      var description='Through '+s.games+' published games · updated '+stamp(s.updatedAt);
      [['Passing','Yds',['Yds','TD','Int']],['Rushing','Yds',['Yds','TD','Avg']],['Receiving','Yds',['Rec','Yds','TD']],['Tackles','Tot Tckls',['Tot Tckls','TFL']],['Sacks','Sacks',['Sacks']]].forEach(function(def){var t=table(def[0]);if(!t)return;var rows=t.rows.filter(function(row){return value(t,row,def[1])!==''&&Number.isFinite(Number(value(t,row,def[1])));}).slice().sort(function(a,b){return Number(value(t,b,def[1]))-Number(value(t,a,def[1]));}),leader=rows[0];if(leader)r.keys.push(fact(def[0].toUpperCase()+' · #'+value(t,leader,'#')+' '+value(t,leader,'Athlete Name')+' — '+def[2].filter(function(k){return value(t,leader,k)!=='';}).map(function(k){return value(t,leader,k)+' '+k;}).join(', ')+'.',s.source,description));});
      var total=table('Total Yards'),pass=table('Passing'),rush=table('Rushing');if(total&&pass&&rush)r.keys.unshift(fact('OFFENSE · '+value(total,total.total,'Y/G')+' yards/game: '+value(rush,rush.total,'Y/G')+' rushing, '+value(pass,pass.total,'Y/G')+' passing (published season totals).',s.source,description));
      var defense=table('Defensive Statistics');if(defense)r.keys.push(fact('DEFENSE · '+value(defense,defense.total,'Int')+' interceptions; '+value(defense,defense.total,'Fmb Rec')+' fumble recoveries reported. Missing source fields are not zero.',s.source,description));
      var lc=team('Lincoln Christian');if(s.games<(lc.schedule.events||[]).filter(function(e){return e.status==='completed';}).length)r.keys.push(fact('STATS COVERAGE WARNING · '+coverageWarning('Lincoln Christian'),s.source,'Checked '+stamp(s.checkedAt)));
    }
    if(fresh&&feed.news)(feed.news.articles||[]).slice(0,2).forEach(function(a){r.lincolnStory.push(fact('OFFICIAL NEWS · '+a.title,a.url,'Article '+a.date+' · headline only','Lincoln athletics'));});
    if(entry)['lincolnStory','opponentStory','keys'].forEach(function(k){r[k]=(entry.sections[k]||[]).concat(r[k]);});return r;
  }
  function has(sport,game){return sport==='football'&&game&&Boolean(researchEntry(game)||feed&&game.date>=day(feed.generatedAt)&&team(game.opponent,game));}
  function mergeRoster(existing,incoming){
    var seen=[];incoming.forEach(function(source){var matches=existing.filter(function(p){return p.sourceId===source.sourceId||norm(p.name)===norm(source.name)&&String(p.number)===String(source.number);});if(!matches.length){var names=existing.filter(function(p){return norm(p.name)===norm(source.name);});if(names.length===1)matches=names;}
      var player=matches[0];if(!player){player={id:'public-'+source.sourceId,note:'',spotlight:false,facts:[]};existing.push(player);}['sourceId','name','number','grade','position','height','weight','profile'].forEach(function(k){if(source[k]!=null)player[k]=source[k];});player.publicRoster=true;player.sourceAbsent=false;seen.push(player.id);
    });existing.forEach(function(p){if(!seen.includes(p.id))p.sourceAbsent=true;});return existing;
  }
  function apply(){if(!api)return;if(document.activeElement&&document.activeElement.matches&&document.activeElement.matches('textarea,input:not([type="checkbox"])')){pending=true;return;}pending=false;if(feed)api.apply(feed);api.render();}
  async function get(file,local){var r=await fetch((local?'':remote)+file+'?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Feed unavailable');return r.json();}
  async function refresh(){if(busy)return;busy=true;if(api)render(api.sport(),api.game());var failed=[];await Promise.all(['football-feed.json','weekly-highlights.json'].map(async function(file){try{var v=await get(file,false);if(file==='football-feed.json'){v=validate(v);if(!feed||new Date(v.generatedAt)>=new Date(feed.generatedAt))feed=v;}else{v=validateCurated(v);if(!curated.generatedAt||v.generatedAt&&new Date(v.generatedAt)>=new Date(curated.generatedAt))curated=v;}}catch(e){failed.push(file==='football-feed.json'?'public football feed':'full research highlights');}}));warning=failed.length?'Could not retrieve the latest '+failed.join(' and ')+'. Showing last available dated data.':'';busy=false;apply();}
  function init(options){api=options;render(api.sport(),api.game());Promise.all(['football-feed.json','weekly-highlights.json'].map(async function(file){try{var v=await get(file,true);if(file==='football-feed.json'){v=validate(v);if(!feed||new Date(v.generatedAt)>new Date(feed.generatedAt))feed=v;}else if(!curated.generatedAt)curated=validateCurated(v);}catch(e){}})).then(apply);refresh();setInterval(function(){if(!document.hidden)refresh();},300000);document.addEventListener('visibilitychange',function(){if(!document.hidden)refresh();});document.addEventListener('focusout',function(){if(pending)setTimeout(apply,0);});document.addEventListener('click',function(e){var b=e.target.closest('#weeklyRefresh,#homeRefresh');if(b)refresh();});}
  window.LincolnWeekly={init:init,render:render,facts:facts,has:has,team:team,pregameRecord:pregameRecord,statData:statData,statDescription:statDescription,coverageWarning:coverageWarning,printMarkup:printMarkup,mergeRoster:mergeRoster,stamp:stamp,validate:validate,validateCurated:validateCurated};
}());
